#tomcat
server:
  port: 8002
spring:
  #服务监控信息
  boot:
    admin:
      client:
        url: "http://localhost:8003"
  #应用名称
  application:
    name: mango-backup
  cloud:
    host: localhost
    port: 8500
    discovery:
      #注册到consul的服务名称
      serviceName: ${spring.application.name}
#服务监控信息 开放全部监控接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
#backup datasource
mango:
  backup:
    datasource:
      host: localhost
      userName: root
      password: root
      database: mango
