server:
  port: 8006
spring:
  application:
    name: mango-consumer
  cloud:
    host: localhost
    port: 8500
    discovery:
      # 注册到consul的服务名称
      serviceName: ${spring.application.name}
  # 服务监控信息
  boot:
    admin:
      client:
        url: "http://localhost:8003"
  #添加ZipKin配置
  zipkin:
    base-url: "http://localhost:9411/"
  sleuth:
    sampler:
      #样品采集数量，默认0.1
      probability: 1
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
# 开启熔断器
feign:
  hystrix:
    enabled: true